### ISSUE TITLE
Twilight forest

### ISSUE THREAD

**Issue by Bamee6** [ultixon/OccultCraft#11]
I'm having an issue entering the portal at all, whenever I attempt to enter the twilight forest and it tells me I cant I have searched and searched and cannot figure out the answer.

**Comment by Bamee6** [comment]
You may enter when the swamp is safe for shrek, what is that supposed to mean?

**Comment by ultixon** [comment]
You need to defeat the swampjaw to enter the twilight forest, the bellringer to enter the nether and the wither for the end. Dimensions are unlocked through quest rewards.
