### ISSUE TITLE
Primal Magick: can't "craft" the 5 dusts for basic calcinator quest

### ISSUE THREAD

**Issue by Crowture** [ultixon/OccultCraft#30]
Playing through the primal magick mod pack and I've gotten to the alchemy discipline. I can complete all other basic quests other than the Basic Calcinator quest. I've used the essence furnace to collect the 5 basic dusts, but the Grimoire doesn't register this.

1.20.1

**Comment by ptrayal** [comment]
I get this too.  Did not get it in 6.2 but do get it in 6.3 version of OccultCraft.

**Comment by ptrayal** [comment]
Still happening in 6.4 and 6.4sf.  
@ultixon - Please fix.  :)

**Comment by ultixon** [comment]
Tried to recreate the issue in 6.6. It seems to be fixed there. Could you see if it works for you as well?

**Comment by ptrayal** [comment]
Yes, it's fixed in 6.6.  Thanks!
