### ISSUE TITLE
Primal Magik issue with Visual Workbench 1.19

### ISSUE THREAD

**Issue by TobiDoes** [ultixon/OccultCraft#4]
So according to the mod discord I found an issue that I have had as well where Visual Workbench makes First Steps impossible to complete do to an interaction issue below is a screenshot of that conversation between daedalus4096 and another user who has had the same issue in just the last 2 weeks
![Screenshot_1](https://user-images.githubusercontent.com/86605096/210909279-21fafc9c-8180-421f-8b55-cb65fb6e9ea7.png)

**Comment by ultixon** [comment]
This is why the workbench is craftable with a recipe.
![image](https://user-images.githubusercontent.com/80710417/211157219-06ae6095-f123-47e1-8625-8057d3e8aa49.png)

**Comment by TobiDoes** [comment]
it wasnt showing up as a craft In JEI
