### ISSUE TITLE
Extra Origins and Origins Classes mod not showing in game

### ISSUE THREAD

**Issue by SpookyScarySkeleton** [ultixon/OccultCraft#5]
As stated in the title. Both of these mods are installed with the modpack, however neither one shows up in game.

**Comment by ultixon** [comment]
On which version are you playing?

**Comment by ultixon** [comment]
I'll need more details in order to possibly resolve your issue.

**Comment by Feralsoul88** [comment]
Hey Ultixion, i have the same issue, im using the 5.6 beta.
origin works but a few are missing these ones appear(merling/blazeborn/enderian/phantom/avian/arachnid/elytrian/feline/shulk/human) and blessings/curses don't appear at all or classes, is this implemented yet in 5.6?

**Comment by ultixon** [comment]
In 5.7, the origins mod and any of its relations have been removed due to many softlocks & other issues. Although I don't think the libra mod (which adds the curses & blessings) is even present in 5.6.
