### ISSUE TITLE
quests

### ISSUE THREAD

**Issue by therealsneezus-christ** [ultixon/OccultCraft#7]
the quest book is just blank

**Comment by ultixon** [comment]
That's because the quests for 5th edition aren't finished yet. If you have any other questions/issues please refer to the FAQ: https://github.com/ultixon/OccultCraft/wiki/FAQ before making an issue.

**Comment by therealsneezus-christ** [comment]
i was on 3rd edition

**Comment by therealsneezus-christ** [comment]
it appears to be working now after i uninstalled and reinstalled it a second time
