### ISSUE TITLE
Game constantly crashing when entering dungeons

### ISSUE THREAD

**Issue by Valetion** [ultixon/OccultCraft#8]
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@609ade27' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]

That's the error message that pops up whenever friends or I enter a dungeon from the "You Are Seeing Dungeons" mod. Is there a fix to this?

**Comment by ultixon** [comment]
Are you playing on the latest version (5.6)?

**Comment by prowler217** [comment]
Im also getting the same error message. playing 5.5

**Comment by ultixon** [comment]
Please try using the 5.6 beta :)
