### ISSUE TITLE
Can not change what item slot I have

### ISSUE THREAD

**Issue by Josephrl13** [ultixon/OccultCraft#9]
So, I am playing occultcraft. I started out normal, then when I was playing I hit ctrl and space and now i can not change my item slots. So i hit like 3 or 4 and it does not change my equipped item slot. I have looked around for a solution and that did not work. I am on windows 11

**Comment by ultixon** [comment]
If I'm not mistaken that is caused from a keybind in the allomancy mod which conflicts with another one.
